# Generated by Django 4.2.2 on 2023-06-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
